name = "PurpleMTR"
author = "AwesomeKalin55, Matcha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6ed44be0a2b14417528a822faa391132bde1b3eb763228a1c5e8eaf048e24d3"

[versions]
fabric = "0.19.3"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
