name = "Project J"
author = "AwesomeKalin55, Jsify"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43e66ced0ed043f96a1fdb856b370a393695c5ddb7fa01bade869238ddeacdf7"

[versions]
fabric = "0.16.5"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
