name = "PurpleMTR"
author = "AwesomeKalin55, Matcha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8df1184f7cebb4171ef24755724132101b7d0b26a26ff8accb8a14c981910e46"

[versions]
fabric = "0.16.14"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
