name = "PurpleMTR"
author = "AwesomeKalin55, Matcha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d4e835fc6a4846fe18400741dabb55c781ceb578676c2cd0cf8840a912d46f7"

[versions]
fabric = "0.16.14"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
