name = "PurpleMTR"
author = "AwesomeKalin55, Matcha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6be736a1dba902c5a67c990249f7e51ff8d141dfa13dc2bfa67bb14600217cf"

[versions]
fabric = "0.16.9"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
